
version: '3.8'

services:
  onemilk-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - kong-net
    restart: unless-stopped
    container_name: onemilk-frontend

networks:
  kong-net:
    external: true
